### PR TITLE
Update "who" page to reflect the new additions to PMC and committers

### PR DESCRIPTION
**Pull request by rafaelweingartner**
Self descriptive PR title ;)

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@swill, could you take a look in this PR?

**Comment by swill** [comment]
LGTM 👍

**Comment by pdion891** [comment]
LGTM :+1:

**Comment by rafaelweingartner** [comment]
@pdion891 thanks ;)
BTW: do you know what happened with our repo at Apache? I was going to merge this one, but it seems that the repo is not there anymore.

**Comment by swill** [comment]
I think this IS the repo now.  :)

**Comment by rafaelweingartner** [comment]
Hmm, I think I cannot merge then. I do not have 2-factor authentication enabled.

**Comment by swill** [comment]
Ahhh, yes. There are a few requirements you have to configure in order to
commit to the apache repos.

Check this thread for instructions.

https://lists.apache.org/thread.html/9fb5894da34e2cc383b2f9b01ab239fd7a5131b90f67c282560ffc5f@
<dev.cloudstack.apache.org>

**Comment by rafaelweingartner** [comment]
Ahh, I cannot activate my 2-factor authentication....
:( all because I do not use cellphones.
someone else would have to merge this one.

**Comment by swill** [comment]
I merged it for you @rafaelweingartner.

**Comment by rafaelweingartner** [comment]
@swill thanks

**Comment by swill** [comment]
Its not looking like the static site has been updated though.  I will give it another 30 minutes and then I will open a ticket with Infra to understand how this site is being updated and what it is using as the source of truth.  I will post back in a bit...

**Comment by rafaelweingartner** [comment]
Now that you mentioned... The repo cloudstack-www was removed, so I wonder if they updated the procedure to publish the site. Remember, the site is/was published from `asf-site` branch.

**Comment by swill** [comment]
Once I understand the updated process I will open a PR to change the README to describe the current update procedure...  I will open an Infra ticket now as I don't think it took this long in the past.

**Comment by swill** [comment]
Infra ticket opened: https://issues.apache.org/jira/browse/INFRA-14559

**Comment by swill** [comment]
BTW, I solved the issue (INFRA ticket is no longer useful).  Check my latest PR for an updated README for contributing:  https://github.com/apache/cloudstack-www/pull/37

**Pull request merged**
