### PR TITLE
Use 'latest' instead of last release number to link release notes

### PR DESCRIPTION
**Pull request by marcaurele**
Signed-off-by: Marc-Aurèle Brothier <m@brothier.org>

### CODE REVIEW

**Comment by marcaurele** [comment]
@rhtyd @rafaelweingartner 
There is still one problem when building the website which is really weird. Instead of using the first release version of the list `4.10` in the data it outputs `4.1` as the first and creates links with `4.10.0.0`. Mysterious Ruby...

**Comment by rafaelweingartner** [comment]
@marcaurele in what link are you seeing this problem?
I just built the master branch now, and it seems to be everything in order.

**Comment by rafaelweingartner** [comment]
Never mind, found the problem

**Comment by rafaelweingartner** [comment]
@marcaurele to fix it you can go to `data/cloudstack.yml` file and change the property from `  branch: 4.10` to `branch: '4.10'`. This problem is caused because the value is being interpreted as a decimal.

**Comment by rafaelweingartner** [comment]
Changing the URL to point to `latest` also works ;)
LGTM

**Comment by marcaurele** [comment]
@rafaelweingartner pushed the fix without PR in master

**Comment by rhtyd** [comment]
I've published the website now.

**Pull request merged**
