### PR TITLE
Typo fix in download url (1 was inserted)

### PR DESCRIPTION
**Pull request by marcaurele**
Signed-off-by: Marc-Aurèle Brothier <m@brothier.org>

### CODE REVIEW

**Comment by marcaurele** [comment]
Doing the build and diff check I found this incorrect link created on the download page. When merge, I'll take care of the website build and update (unless I'll find other errors). cc @rhtyd @rafaelweingartner

**Comment by rafaelweingartner** [comment]
LGTM
@marcaurele thanks!

**Comment by rhtyd** [comment]
Lgtm

**Comment by rafaelweingartner** [comment]
@rhtyd and @marcaurele the process to merge these PRs in `cloudstack-www` is a little bit different.
There is a section in the README called "COMMITTER: Merge & Deploy" that details it.

Basically after merging the PR into master, we need to "compile" the source and then commit and merge it into `asf-site` branch. CloudStack website is published from that branch.

**Comment by rhtyd** [comment]
Rafael, I'm aware I'll do this tomorrow morning.

**Comment by rafaelweingartner** [comment]
Ah, ok..Thanks!

**Pull request merged**
