### PR TITLE
Inclusivity changes for CloudStack - Renamed default git branch name from 'master' to 'main', and some offensive words/terms as appropriate.

### PR DESCRIPTION
**Pull request by sureshanaparti**
Inclusivity changes for CloudStack -  Renamed default git branch name from 'master' to 'main', and some offensive words/terms as appropriate.

### CODE REVIEW

**Review by nathanmcgarvey — CHANGES_REQUESTED** [review]
Why is this file a part of this pull request? It seems to be unrelated to the subject in the request. Possibly a commit that wasn't supposed to be a part of this PR?

**Comment by DaanHoogland** [comment]
what file do you speak of @nathanmcgarvey ? github says 22383 files are involved :eyes:

**Comment by nathanmcgarvey** [comment]
@DaanHoogland Sorry about that... the newsletter.txt file that is the entire first commit in this pull request. (Oct 17, 2020)

**Comment by nathanmcgarvey** [comment]
22383 files with over 44000 lines changed in a single commit may hurt repo-wise... if this is merged, ensure that repo packing, garbage collecting, and index-updating is done and maybe a comparison of pre-merge to post-merge size is evaluated. Also, there is *no* way anybody is reasonably doing a human review on this for real. :)

Alternatively, do we really need to be updating the HTML tags for 4.0.0 API documentation from [8?] years ago? Maybe it would be better to just age it off, or put a readme about terminology changes and just change 4.14+ versions. Otherwise, I could see this becoming a repeated effort if other terms are deemed "offensive" in the future. And I'd really rather not start having tens of thousands of changed source code lines be "normal" behavior for a source code repo.

**Comment by sureshanaparti** [comment]
> 22383 files with over 44000 lines changed in a single commit may hurt repo-wise... if this is merged, ensure that repo packing, garbage collecting, and index-updating is done and maybe a comparison of pre-merge to post-merge size is evaluated. Also, there is _no_ way anybody is reasonably doing a human review on this for real. :)
> 
> Alternatively, do we really need to be updating the HTML tags for 4.0.0 API documentation from [8?] years ago? Maybe it would be better to just age it off, or put a readme about terminology changes and just change 4.14+ versions. Otherwise, I could see this becoming a repeated effort if other terms are deemed "offensive" in the future. And I'd really rather not start having tens of thousands of changed source code lines be "normal" behavior for a source code repo.

@nathanmcgarvey Thanks for the review, will remove the relevant changes from the old apidocs.

**Comment by rhtyd** [comment]
@sureshanaparti pl address changes

**Comment by sureshanaparti** [comment]
> Why is this file a part of this pull request? It seems to be unrelated to the subject in the request. Possibly a commit that wasn't supposed to be a part of this PR?

Thanks @nathanmcgarvey , this change is unrelated and removed.

**Comment by sureshanaparti** [comment]
> > 22383 files with over 44000 lines changed in a single commit may hurt repo-wise... if this is merged, ensure that repo packing, garbage collecting, and index-updating is done and maybe a comparison of pre-merge to post-merge size is evaluated. Also, there is _no_ way anybody is reasonably doing a human review on this for real. :)
> > Alternatively, do we really need to be updating the HTML tags for 4.0.0 API documentation from [8?] years ago? Maybe it would be better to just age it off, or put a readme about terminology changes and just change 4.14+ versions. Otherwise, I could see this becoming a repeated effort if other terms are deemed "offensive" in the future. And I'd really rather not start having tens of thousands of changed source code lines be "normal" behavior for a source code repo.
> 
> @nathanmcgarvey Thanks for the review, will remove the relevant changes from the old apidocs.

@nathanmcgarvey @DaanHoogland Removed the changes in the old api doc references (not relevant now).

**Comment by sureshanaparti** [comment]
> > > 22383 files with over 44000 lines changed in a single commit may hurt repo-wise... if this is merged, ensure that repo packing, garbage collecting, and index-updating is done and maybe a comparison of pre-merge to post-merge size is evaluated. Also, there is _no_ way anybody is reasonably doing a human review on this for real. :)
> > > Alternatively, do we really need to be updating the HTML tags for 4.0.0 API documentation from [8?] years ago? Maybe it would be better to just age it off, or put a readme about terminology changes and just change 4.14+ versions. Otherwise, I could see this becoming a repeated effort if other terms are deemed "offensive" in the future. And I'd really rather not start having tens of thousands of changed source code lines be "normal" behavior for a source code repo.
> > 
> > 
> > @nathanmcgarvey Thanks for the review, will remove the relevant changes from the old apidocs.
> 
> @nathanmcgarvey @DaanHoogland Removed the changes in the old api doc references (not relevant now).

@nathanmcgarvey are you LGTM with the changes?

**Comment by nathanmcgarvey** [comment]
> > > > 22383 files with over 44000 lines changed in a single commit may hurt repo-wise... if this is merged, ensure that repo packing, garbage collecting, and index-updating is done and maybe a comparison of pre-merge to post-merge size is evaluated. Also, there is _no_ way anybody is reasonably doing a human review on this for real. :)
> > > > Alternatively, do we really need to be updating the HTML tags for 4.0.0 API documentation from [8?] years ago? Maybe it would be better to just age it off, or put a readme about terminology changes and just change 4.14+ versions. Otherwise, I could see this becoming a repeated effort if other terms are deemed "offensive" in the future. And I'd really rather not start having tens of thousands of changed source code lines be "normal" behavior for a source code repo.
> > > 
> > > 
> > > @nathanmcgarvey Thanks for the review, will remove the relevant changes from the old apidocs.
> > 
> > 
> > @nathanmcgarvey @DaanHoogland Removed the changes in the old api doc references (not relevant now).
> 
> @nathanmcgarvey are you LGTM with the changes?

Yep. LGTM.

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
Merging this but we won't update the website (asf-site branch) until the main repo's branch is change to `main`

**Pull request merged**
