### PR TITLE
Refactor: fix twitter, who, announcements, make events (more) dynamic - ( content unchanged)

### PR DESCRIPTION
**Pull request by PaulAngus**
Refactor (content unchanged)

- fix twitter feed; twitter have made custom feeds require oauth for api1.1 - this uses public widget which only shows @cloudstack tweets, which does not require oauth
- "who we are" formatting is fixed
- announcements from cloudstack atom feed rewritten as was broken
- The 'events' are pulled from a raw csv file in github (https://raw.githubusercontent.com/apache/cloudstack-www/master/data/acs-events.csv) Therefore THE SITE DOES NOT NEED TO BE REBUILT for upcoming events to be changed.

This refactor can CURRENTLY be reviewed at https://acs-www.shapeblue.com/www/

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
Can you remove the compiled (HTML) files from this PR (as described in the README)? This will make our lives easier to review.

**Comment by PaulAngus** [comment]
@rafaelweingartner it doesn't say to do that in the readme.md that I can see.
The 'content' dir is already in the source.
Taking it out using this PR will make it really unreadable,

I suggest we take all of the 'content' contents out as a separate PR, and then add a git ignore.

**Comment by rafaelweingartner** [comment]
Yes, I checked the README just now. I had worked on these guidelines a long time ago, and I thought that it was written not to add "compiled" code to master, but it is not.

When I asked to remove the compiled version, I meant only in your commit. You can for instance only commit the "soure" files (the source files you changed), and then you leave the commit of the compiled code when you merge the PR.

**Comment by sbrueseke** [comment]
LGTM

**Pull request merged**
