### PR TITLE
cmk6.3.0 release changes

### PR DESCRIPTION
**Pull request by borisstoyanov**
cmk6.3 release changes

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@borisstoyanov this is public now but just realised https://archive.apache.org/dist/cloudstack/releases/cloudmonkey-6.2.0/  and in https://archive.apache.org/dist/cloudstack/releases/cloudmonkey-6.1.0/ in it we've sha512 - shouldn't the checksums be sha512?

**Comment by borisstoyanov** [comment]
ok let me change that, will add the files and add changes here

**Comment by rohityadavcloud** [comment]
Thanks @borisstoyanov unfortunately you may need to send another PR to the asf-site branch.

**Comment by borisstoyanov** [comment]
yeah sry, thats' what I've meant

**Pull request merged**
