### PR TITLE
update download URL

### PR DESCRIPTION
**Pull request by pdion891**
Update download URL because of change on apache servers.

### CODE REVIEW

**Comment by pdion891** [comment]
Will do directly as the site is impacted.

**Comment by terbolous** [comment]
Looks good to me, but have we been informed of this change from infra? Did a search for closer.cgi and closer.lua in my mailbox, and the only reference I found was git commit messages from infra-puppet @ke4qqq

**Comment by runseb** [comment]
@terbolous yes, there was a DDOS against ASF servers and the PMC was informed.

**Comment by terbolous** [comment]
@runseb Ok, no worries then :-)

**Pull request closed without merging**
