### PR TITLE
Moved Remi to PMC list

### PR DESCRIPTION
**Pull request by thinktwo**

### CODE REVIEW

**Comment by ke4qqq** [comment]
LGTM

**Comment by remibergsma** [comment]
LGTM ;-)

**Comment by terbolous** [comment]
There's a small discrepancy about how to list PMC members.
Previous to this[1] commit, they were listed in a separate table (moved from committers to pmc upon election), but with the commit[1] it was changed to list PMC members as both PMC and committers.

There's nothing wrong with that, I just feel we should settle on one way to do it so we don't end up undoing/re-doing each others work.

Personally I'm in favor of listing PMC members twice, that is also how it is done at https://projects-new.apache.org/committee.html?cloudstack

@bhaisaab left an url to a script that automatically prints the table, but I guess you need an Apache ID to query LDAP?

[1] https://github.com/apache/cloudstack-www/commit/3458edbfb0612e1dfaae92b01ca32256f640bbac

**Comment by ke4qqq** [comment]
Well I just committed this change, prior to seeing @terbolous comment. - so I'll close this, but we do indeed need to figure out how we want to do this.

**Comment by terbolous** [comment]
It wasn't meant as a -1 vote really, just a note that there's a discrepancy that should be settled. Remi does after all belong in the PMC table :-)

**Comment by ke4qqq** [comment]
I didn't take it as a -1, or I would have reverted my change. I just finished pushing the change and didn't want you to think I was ignoring your comment. It is valid, and I didn't notice it until you pointed it out.

**Comment by bhaisaab** [comment]
@terbolous yes, if you're a PMC you can run this by logging into people.apache.org;
https://people.apache.org/~bhaisaab/cloudstack/makewholist.sh

this is general purpose and can be used for any project; in our case you run it as:
bash makewholist.sh cloudstack

This will generate the PMC and committer table/list.

**Comment by terbolous** [comment]
I like having tools that help us do the job right, and equally, every time.
However, if we were to choose an official tool for the job it should be usable by everyone. Not everyone of us are PMCs after all.

projects-new.a.o has a site with all the members[1], we could check with ComDev (who AFAIK made it) if it would be possible to export it to JSON or something similar so that we won't have to webscrape.

That would be accessible by any contributor, and make sure we do this in a consistent way.

[1]  https://projects-new.apache.org/committee.html?cloudstack

**Pull request closed without merging**
