### PR TITLE
Change mailing list search mechanism in CloudStack's web site

### PR DESCRIPTION
**Pull request by rafaelweingartner**
I am replacing the Markmail search mechanism by the Apache's one, which is better.
Because the HTML form tag on submit will escape query string elements, I needed to hack around, and therefore a simple FORM element would not work.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@rafaelweingartner it looks fine but i am awkward with pr. how do i test this?

**Comment by rafaelweingartner** [comment]
If you want to test it locally, you would need to follow the instructions to build and test locally. 

It should be something like this after you pulled the branch:
```
./build.sh
middleman server [-p <portnumber>]
```

**Comment by rafaelweingartner** [comment]
I did not understand. What other links?

**Comment by waza-ari** [comment]
Hi, I have reviewed the PR and for me it looks fine. Local testing worked, I could search the mailing lists.

One more suggestion: I would update the links in `source/mailing-lists.markdown` as well (lines 23 through 28 and 32). 

They are referring to http://mail-archives.apache.org/mod_mbox/cloudstack-announce/, they could refer to the new archive as well

**Comment by rafaelweingartner** [comment]
ah, now I understood what @DaanHoogland meant. Thanks @waza-ari

**Comment by DaanHoogland** [comment]
yeah sorry, communicating to people comes hard on me these days;)

**Comment by rafaelweingartner** [comment]
Done. Can you guys confirm that you are ok with these other changes as well?

**Comment by waza-ari** [comment]
@rafaelweingartner looks good, thank you. +1 from me.

**Comment by rafaelweingartner** [comment]
@DaanHoogland are you going to publish the website as well?

**Comment by DaanHoogland** [comment]
@rafaelweingartner :)
wouw, another thing to learn, yes I will go through that doc and see to it.

**Comment by rafaelweingartner** [comment]
Awesome, thanks.
If you have any problems you can ping me.

**Pull request merged**
