### PR TITLE
Update committers and PMCs list

### PR DESCRIPTION
**Pull request by rafaelweingartner**

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
@PaulAngus I noticed that you tried to update the 'who' list. I extended the script to receive a parameter and automatically exclude the emeritus now. This will facilitate when building the list of PMCs and users.

**Comment by rafaelweingartner** [comment]
@PaulAngus I noticed that you tried to update the 'who' list. I extended the script to receive a parameter and automatically exclude the emeritus now. This will facilitate when building the list of PMCs and users.

**Comment by PaulAngus** [comment]
Thanks Rafael,

I’m actually looking at borrowing the js from the Apache phonebook page and embedding that (fixed to just the CloudStack project), then we never have to touch the page again.

**Comment by rafaelweingartner** [comment]
That is an awesome idea.

**Pull request merged**
