### PR TITLE
Updated list with makewholist.py

### PR DESCRIPTION
**Pull request by jannyg**

### CODE REVIEW

**Comment by pdion891** [comment]
LGTM

**Comment by terbolous** [comment]
Some of these are moved from emeritus to active with this commit

**Comment by terbolous** [comment]
My bad, they aren't actually removed from the emeritus list, just added to the active list.

**Comment by rafaelweingartner** [comment]
LGTM

**Comment by rafaelweingartner** [comment]
Before this PR reaches its one year of age, I will merge this tomorrow if no one objects.

**Pull request merged**
